package us.myles.cb;

import us.myles.classtrap.TrapTag;

//org.bukkit.craftbukkit.v1_7_R3.CraftWorld
@TrapTag
public interface CraftWorld {
	public boolean equals(java.lang.Object arg0);
	public java.lang.String toString();
	public int hashCode();
	public java.lang.String getName();
	public long getId();
	public void save();
	public us.myles.nms.WorldServer getHandle();
	public long getTime();
	public void setTime(long arg0);
	public void setMetadata(java.lang.String arg0, org.bukkit.metadata.MetadataValue arg1);
	public boolean hasMetadata(java.lang.String arg0);
	public void playEffect(org.bukkit.Location arg0, org.bukkit.Effect arg1, java.lang.Object arg2);
	public void playEffect(org.bukkit.entity.Player arg0, org.bukkit.Effect arg1, int arg2);
	public void playEffect(org.bukkit.Location arg0, org.bukkit.Effect arg1, int arg2);
	public void playEffect(org.bukkit.Location arg0, org.bukkit.Effect arg1, int arg2, int arg3);
	public void playEffect(org.bukkit.Location arg0, org.bukkit.Effect arg1, java.lang.Object arg2, int arg3);
	public org.bukkit.WorldType getWorldType();
	public java.util.List getMetadata(java.lang.String arg0);
	public java.lang.String[] getGameRules();
	public org.bukkit.block.Biome getBiome(int arg0, int arg1);
	public org.bukkit.Chunk getChunkAt(org.bukkit.block.Block arg0);
	public org.bukkit.Chunk getChunkAt(org.bukkit.Location arg0);
	public org.bukkit.Chunk getChunkAt(int arg0, int arg1);
	public java.util.List getEntities();
	public boolean hasStorm();
	public org.bukkit.block.Block getBlockAt(int arg0, int arg1, int arg2);
	public org.bukkit.block.Block getBlockAt(org.bukkit.Location arg0);
	public void setStorm(boolean arg0);
	public void setThundering(boolean arg0);
	public boolean isThundering();
	public void setSpawnFlags(boolean arg0, boolean arg1);
	public long getSeed();
	public org.bukkit.entity.Item dropItemNaturally(org.bukkit.Location arg0, org.bukkit.inventory.ItemStack arg1);
	public boolean getKeepSpawnInMemory();
	public double getTemperature(int arg0, int arg1);
	public java.util.List getLivingEntities();
	public boolean getAllowMonsters();
	public org.bukkit.entity.FallingBlock spawnFallingBlock(org.bukkit.Location arg0, int arg1, byte arg2);
	public org.bukkit.entity.FallingBlock spawnFallingBlock(org.bukkit.Location arg0, org.bukkit.Material arg1, byte arg2);
	public org.bukkit.ChunkSnapshot getEmptyChunkSnapshot(int arg0, int arg1, boolean arg2, boolean arg3);
	public void setKeepSpawnInMemory(boolean arg0);
	public boolean regenerateChunk(int arg0, int arg1);
	public java.io.File getWorldFolder();
	public boolean canGenerateStructures();
	public void setTicksPerAnimalSpawns(int arg0);
	public boolean unloadChunkRequest(int arg0, int arg1, boolean arg2);
	public boolean unloadChunkRequest(int arg0, int arg1);
	public void setTicksPerMonsterSpawns(int arg0);
	public void setMonsterSpawnLimit(int arg0);
	public java.lang.String getGameRuleValue(java.lang.String arg0);
	public boolean setGameRuleValue(java.lang.String arg0, java.lang.String arg1);
	public void setAmbientSpawnLimit(int arg0);
	public org.bukkit.Chunk[] getLoadedChunks();
	public org.bukkit.entity.LightningStrike strikeLightningEffect(org.bukkit.Location arg0);
	public java.util.Collection getEntitiesByClasses(java.lang.Class[] arg0);
	public boolean setSpawnLocation(int arg0, int arg1, int arg2);
	public org.bukkit.World.Environment getEnvironment();
	public void setAnimalSpawnLimit(int arg0);
	public org.bukkit.block.Block getHighestBlockAt(int arg0, int arg1);
	public org.bukkit.block.Block getHighestBlockAt(org.bukkit.Location arg0);
	public java.util.Collection getEntitiesByClass(java.lang.Class[] arg0);
	public java.util.Collection getEntitiesByClass(java.lang.Class arg0);
	public org.bukkit.Location getSpawnLocation();
	public void setWaterAnimalSpawnLimit(int arg0);
	public boolean getAllowAnimals();
	public java.util.UUID getUID();
	public boolean isChunkInUse(int arg0, int arg1);
	public long getFullTime();
	public boolean refreshChunk(int arg0, int arg1);
	public org.bukkit.generator.ChunkGenerator getGenerator();
	public void setAutoSave(boolean arg0);
	public org.bukkit.entity.Item dropItem(org.bukkit.Location arg0, org.bukkit.inventory.ItemStack arg1);
	public void setFullTime(long arg0);
	public boolean isAutoSave();
	public void setDifficulty(org.bukkit.Difficulty arg0);
	public boolean isGameRule(java.lang.String arg0);
	public org.bukkit.entity.LivingEntity spawnCreature(org.bukkit.Location arg0, org.bukkit.entity.CreatureType arg1);
	public org.bukkit.entity.LivingEntity spawnCreature(org.bukkit.Location arg0, org.bukkit.entity.EntityType arg1);
	public void setBiome(int arg0, int arg1, org.bukkit.block.Biome arg2);
	public double getHumidity(int arg0, int arg1);
	public boolean generateTree(org.bukkit.Location arg0, org.bukkit.TreeType arg1);
	public boolean generateTree(org.bukkit.Location arg0, org.bukkit.TreeType arg1, org.bukkit.BlockChangeDelegate arg2);
	public boolean unloadChunk(int arg0, int arg1, boolean arg2);
	public boolean unloadChunk(int arg0, int arg1, boolean arg2, boolean arg3);
	public boolean unloadChunk(int arg0, int arg1);
	public boolean unloadChunk(org.bukkit.Chunk arg0);
	public org.bukkit.Difficulty getDifficulty();
	public boolean getPVP();
	public int getMaxHeight();
	public java.util.List getPlayers();
	public void setPVP(boolean arg0);
	public void loadChunk(org.bukkit.Chunk arg0);
	public boolean loadChunk(int arg0, int arg1, boolean arg2);
	public void loadChunk(int arg0, int arg1);
	public org.bukkit.entity.Arrow spawnArrow(org.bukkit.Location arg0, org.bukkit.util.Vector arg1, float arg2, float arg3);
	public void playSound(org.bukkit.Location arg0, org.bukkit.Sound arg1, float arg2, float arg3);
	public java.util.List getPopulators();
	public org.bukkit.entity.Entity spawnEntity(org.bukkit.Location arg0, org.bukkit.entity.EntityType arg1);
	public boolean isChunkLoaded(org.bukkit.Chunk arg0);
	public boolean isChunkLoaded(int arg0, int arg1);
	public int getBlockTypeIdAt(int arg0, int arg1, int arg2);
	public int getBlockTypeIdAt(org.bukkit.Location arg0);
	public long getTicksPerAnimalSpawns();
	public void removeMetadata(java.lang.String arg0, org.bukkit.plugin.Plugin arg1);
	public long getTicksPerMonsterSpawns();
	public int getMonsterSpawnLimit();
	public int getAnimalSpawnLimit();
	public int getWaterAnimalSpawnLimit();
	public int getAmbientSpawnLimit();
	public org.bukkit.entity.LightningStrike strikeLightning(org.bukkit.Location arg0);
	public void setThunderDuration(int arg0);
	public int getWeatherDuration();
	public void setWeatherDuration(int arg0);
	public int getHighestBlockYAt(org.bukkit.Location arg0);
	public int getHighestBlockYAt(int arg0, int arg1);
	public boolean createExplosion(org.bukkit.Location arg0, float arg1);
	public boolean createExplosion(org.bukkit.Location arg0, float arg1, boolean arg2);
	public boolean createExplosion(double arg0, double arg1, double arg2, float arg3);
	public boolean createExplosion(double arg0, double arg1, double arg2, float arg3, boolean arg4, boolean arg5);
	public boolean createExplosion(double arg0, double arg1, double arg2, float arg3, boolean arg4);
	public int getThunderDuration();
	public void processChunkGC();
	public void sendPluginMessage(org.bukkit.plugin.Plugin arg0, java.lang.String arg1, byte[] arg2);
	public java.util.Set getListeningPluginChannels();
	public int getSeaLevel();
	public org.bukkit.entity.Entity spawn(org.bukkit.Location arg0, java.lang.Class arg1);
	public org.bukkit.entity.Entity spawn(org.bukkit.Location arg0, java.lang.Class arg1, org.bukkit.event.entity.CreatureSpawnEvent.SpawnReason arg2);
	public us.myles.cb.metadata.BlockMetadataStore getBlockMetadata();
	public void setEnvironment(org.bukkit.World.Environment arg0);
	public us.myles.nms.TileEntity getTileEntityAt(int arg0, int arg1, int arg2);
}
