package us.myles.nms;

import us.myles.classtrap.TrapTag;

//net.minecraft.server.v1_7_R3.Entity
@TrapTag
public interface Entity {
	public boolean equals(java.lang.Object arg0);
	public java.lang.String toString();
	public int hashCode();
	public void B();
	public int C();
	public AxisAlignedBB I();
	public java.lang.String getName();
	public int getId();
	public boolean isAlive();
	public boolean c(NBTTagCompound arg0);
	public boolean c(double arg0, double arg1, double arg2);
	public boolean c(EntityHuman arg0);
	public AxisAlignedBB h(Entity arg0);
	public void h();
	public void b(Entity arg0, int arg1);
	public void b(int arg0);
	public void k(Entity arg0);
	public boolean j(Entity arg0);
	public double e(double arg0, double arg1, double arg2);
	public void e(NBTTagCompound arg0);
	public float e(Entity arg0);
	public void e(boolean arg0);
	public void a(CrashReportSystemDetails arg0);
	public EntityItem a(ItemStack arg0, float arg1);
	public boolean a(Explosion arg0, World arg1, int arg2, int arg3, int arg4, Block arg5, float arg6);
	public EntityItem a(Item arg0, int arg1);
	public EntityItem a(Item arg0, int arg1, float arg2);
	public void a(EntityLightning arg0);
	public void a(EntityLiving arg0);
	public float a(Explosion arg0, World arg1, int arg2, int arg3, int arg4, Block arg5);
	public void a(Entity arg0, boolean arg1);
	public void a(float arg0, float arg1, float arg2);
	public boolean a(Material arg0);
	public void setPosition(double arg0, double arg1, double arg2);
	public boolean d(NBTTagCompound arg0);
	public void d(int arg0);
	public float d(float arg0);
	public void g(double arg0, double arg1, double arg2);
	public boolean i(Entity arg0);
	public void i(int arg0);
	public void W();
	public boolean isInvulnerable();
	public void setPassengerOf(Entity arg0);
	public void setPositionRotation(double arg0, double arg1, double arg2, float arg3, float arg4);
	public us.myles.cb.entity.CraftEntity getBukkitEntity();
	public void mount(Entity arg0);
	public boolean damageEntity(DamageSource arg0, float arg1);
	public float getHeadHeight();
	public void die();
	public void ar();
	public double f(double arg0, double arg1, double arg2);
	public void f(NBTTagCompound arg0);
	public double f(Entity arg0);
	public void spawnIn(World arg0);
	public Vec3D af();
	public boolean L();
	public boolean isSprinting();
	public void extinguish();
	public boolean isBurning();
	public void makeSound(java.lang.String arg0, float arg1, float arg2);
	public void aa();
	public boolean isSneaking();
	public int ah();
	public boolean M();
	public void b_(EntityHuman arg0);
	public void setSneaking(boolean arg0);
	public IChatBaseComponent getScoreboardDisplayName();
	public double ac();
	public boolean au();
	public void setOnFire(int arg0);
	public void setSprinting(boolean arg0);
	public ItemStack[] getEquipment();
	public boolean aB();
	public boolean inBlock();
	public boolean al();
	public void setEquipment(int arg0, ItemStack arg1);
	public int aw();
	public boolean ay();
	public DataWatcher getDataWatcher();
	public float getHeadRotation();
	public void teleportTo(org.bukkit.Location arg0, boolean arg1);
	public int ax();
	public float ae();
	public double ad();
	public void ab();
	public boolean isInvisible();
	public boolean K();
	public int getAirTicks();
	public void setAirTicks(int arg0);
	public void setInvisible(boolean arg0);
	public boolean isFireproof();
	public void collide(Entity arg0);
	public Entity[] as();
	public boolean R();
	public void move(double arg0, double arg1, double arg2);
	public boolean O();
	public boolean Q();
	public void ag();
	public void setLocation(double arg0, double arg1, double arg2, float arg3, float arg4);
	public java.util.UUID getUniqueID();
}
