package us.myles.nms;

import us.myles.classtrap.TrapTag;
import us.myles.classtrap.TrapTagType;

//net.minecraft.server.v1_7_R3.EntityHuman
@TrapTag
public interface EntityHuman {
	public int C();
	public java.lang.String getName();
	public ItemStack r(int arg0);
	public void c(Entity arg0);
	public void h();
	public void m(float arg0);
	public void b(Entity arg0, int arg1);
	public void b(IChatBaseComponent arg0);
	public void b(ItemStack arg0);
	public void b(Entity arg0);
	public void b(NBTTagCompound arg0);
	public void e(float arg0, float arg1);
	public void e();
	public void a(TileEntity arg0);
	public void a(CommandBlockListenerAbstract arg0);
	public EnumBedResult a(int arg0, int arg1, int arg2);
	public EntityItem a(boolean arg0);
	public boolean a(EntityHuman arg0);
	public void a(NBTTagCompound arg0);
	public boolean a(Block arg0);
	public float a(Block arg0, boolean arg1);
	public EntityItem a(ItemStack arg0, boolean arg1, boolean arg2);
	public void a(EntityLiving arg0);
	public void a(float arg0);
	public void a(ItemStack arg0, int arg1);
	public boolean a(int arg0, int arg1, int arg2, int arg3, ItemStack arg4);
	public void a(EnumGamemode arg0);
	public void a(Statistic arg0, int arg1);
	public void a(Statistic arg0);
	public void a(boolean arg0, boolean arg1, boolean arg2);
	public boolean bQ();
	public boolean d(int arg0, int arg1, int arg2);
	public boolean g(boolean arg0);
	public void startEnchanting(int arg0, int arg1, int arg2, java.lang.String arg3);
	public void setPassengerOf(Entity arg0);
	public us.myles.cb.entity.CraftEntity getBukkitEntity();
	@TrapTag(type = TrapTagType.METHOD, value = "getBukkitEntity")
	public us.myles.cb.entity.CraftHumanEntity getBukkitEntity2();
	public void closeInventory();
	public void openHorseInventory(EntityHorse arg0, IInventory arg1);
	public void openMinecartHopper(EntityMinecartHopper arg0);
	public void openBrewingStand(TileEntityBrewingStand arg0);
	public boolean isSleeping();
	public void openContainer(IInventory arg0);
	public void openBeacon(TileEntityBeacon arg0);
	public void mount(Entity arg0);
	public void openAnvil(int arg0, int arg1, int arg2);
	public void openHopper(TileEntityHopper arg0);
	public void openFurnace(TileEntityFurnace arg0);
	public void openTrade(IMerchant arg0, java.lang.String arg1);
	public void openDispenser(TileEntityDispenser arg0);
	public boolean damageEntity(DamageSource arg0, float arg1);
	public void startCrafting(int arg0, int arg1, int arg2);
	public World getWorld();
	public float getHeadHeight();
	public void die();
	public void die(DamageSource arg0);
	public ChunkCoordinates getBed();
	public void levelDown(int arg0);
	public void ar();
	public float br();
	public boolean isBlocking();
	public boolean bx();
	public void bz();
	public void makeSound(java.lang.String arg0, float arg1, float arg2);
	public void aa();
	public float bD();
	public int ah();
	public void bA();
	public Scoreboard getScoreboard();
	public ItemStack bd();
	public void giveExp(int arg0);
	public void copyTo(EntityHuman arg0, boolean arg1);
	public int getScore();
	public void setScore(int arg0);
	public void addScore(int arg0);
	public GameProfile getProfile();
	public void updateAbilities();
	public ScoreboardTeamBase getScoreboardTeam();
	public boolean isRespawnForced();
	public void setRespawnPosition(ChunkCoordinates arg0, boolean arg1);
	public IChatBaseComponent getScoreboardDisplayName();
	public boolean isDeeplySleeping();
	public ItemStack bE();
	public double ac();
	public void attack(Entity arg0);
	public void bF();
	public EntityItem drop(ItemStack arg0, boolean arg1);
	public boolean q(Entity arg0);
	public int aU();
	public int getExpToLevel();
	public InventoryEnderChest getEnderChest();
	public ItemStack getEquipment(int arg0);
	public ItemStack[] getEquipment();
	public float bk();
	public boolean aB();
	public boolean inBlock();
	public void checkMovement(double arg0, double arg1, double arg2);
	public FoodMetaData getFoodData();
	public void setEquipment(int arg0, ItemStack arg1);
	public void bi();
}
