package us.myles.cb.entity;

import us.myles.classtrap.TrapTag;
import us.myles.classtrap.TrapTagType;

//org.bukkit.craftbukkit.v1_7_R3.entity.CraftPlayer
@TrapTag
public interface CraftPlayer {
	public boolean equals(java.lang.Object arg0);
	public java.lang.String toString();
	public int hashCode();
	public java.net.InetSocketAddress getAddress();
	public org.bukkit.entity.EntityType getType();
	public us.myles.nms.Entity getHandle();
	@TrapTag(type = TrapTagType.METHOD, value = "getHandle")
	public us.myles.nms.EntityHuman getHandle2();
	@TrapTag(type = TrapTagType.METHOD, value = "getHandle")
	public us.myles.nms.EntityPlayer getHandle3();
	@TrapTag(type = TrapTagType.METHOD, value = "getHandle")
	public us.myles.nms.EntityLiving getHandle4();
	public void setHandle(us.myles.nms.EntityPlayer arg0);
	public java.lang.String getDisplayName();
	public boolean teleport(org.bukkit.Location arg0, org.bukkit.event.player.PlayerTeleportEvent.TeleportCause arg1);
	public void setMetadata(java.lang.String arg0, org.bukkit.metadata.MetadataValue arg1);
	public boolean hasMetadata(java.lang.String arg0);
	public void playEffect(org.bukkit.Location arg0, org.bukkit.Effect arg1, int arg2);
	public void playEffect(org.bukkit.Location arg0, org.bukkit.Effect arg1, java.lang.Object arg2);
	public java.util.List getMetadata(java.lang.String arg0);
	public float getScaledHealth();
	public void updateScaledHealth();
	public void updateInventory();
	public void sendMessage(java.lang.String[] arg0);
	public void sendMessage(java.lang.String arg0);
	public void setGameMode(org.bukkit.GameMode arg0);
	public double getHealth();
	public void disconnect(java.lang.String arg0);
	public void readExtraData(us.myles.nms.NBTTagCompound arg0);
	public org.bukkit.entity.Player getPlayer();
	public org.bukkit.GameMode getGameMode();
	public void setExtraData(us.myles.nms.NBTTagCompound arg0);
	public boolean isSprinting();
	public boolean isSneaking();
	public org.bukkit.scoreboard.Scoreboard getScoreboard();
	@TrapTag(type = TrapTagType.METHOD, value = "getScoreboard")
	public us.myles.cb.scoreboard.CraftScoreboard getScoreboard2();
	public void giveExp(int arg0);
	public boolean isOp();
	public us.myles.nms.GameProfile getProfile();
	public long getPlayerTime();
	public void setSneaking(boolean arg0);
	public void setPlayerWeather(org.bukkit.WeatherType arg0);
	public void setResourcePack(java.lang.String arg0);
	public void resetPlayerWeather();
	public org.bukkit.WeatherType getPlayerWeather();
	public void setSprinting(boolean arg0);
	public boolean isFlying();
	public void playNote(org.bukkit.Location arg0, org.bukkit.Instrument arg1, org.bukkit.Note arg2);
	public void playNote(org.bukkit.Location arg0, byte arg1, byte arg2);
	public boolean hasPlayedBefore();
	public long getFirstPlayed();
	public void setWhitelisted(boolean arg0);
	public org.bukkit.Location getBedSpawnLocation();
	public boolean setWindowProperty(org.bukkit.inventory.InventoryView.Property arg0, int arg1);
	public void resetMaxHealth();
	public int getNoDamageTicks();
	public boolean isOnline();
	public void saveData();
	public boolean isBanned();
	public void playSound(org.bukkit.Location arg0, java.lang.String arg1, float arg2, float arg3);
	public void playSound(org.bukkit.Location arg0, org.bukkit.Sound arg1, float arg2, float arg3);
	public void setRealHealth(double arg0);
	public void kickPlayer(java.lang.String arg0);
	public void removeMetadata(java.lang.String arg0, org.bukkit.plugin.Plugin arg1);
	public boolean getAllowFlight();
	public void sendPluginMessage(org.bukkit.plugin.Plugin arg0, java.lang.String arg1, byte[] arg2);
	public java.util.Set getListeningPluginChannels();
	public void setPlayerTime(long arg0, boolean arg1);
	public float getSaturation();
	public void setFlying(boolean arg0);
	public void setWalkSpeed(float arg0);
	public void setFoodLevel(int arg0);
	public void showPlayer(org.bukkit.entity.Player arg0);
	public float getExp();
	public void setExhaustion(float arg0);
	public void addChannel(java.lang.String arg0);
	public float getExhaustion();
	public void giveExpLevels(int arg0);
	public void setSaturation(float arg0);
	public int getFoodLevel();
	public void setLevel(int arg0);
	public float getWalkSpeed();
	public void setFlySpeed(float arg0);
	public void removeChannel(java.lang.String arg0);
	public void setExp(float arg0);
	public boolean isConversing();
	public void setScoreboard(org.bukkit.scoreboard.Scoreboard arg0);
	public int getStatistic(org.bukkit.Statistic arg0);
	public int getStatistic(org.bukkit.Statistic arg0, org.bukkit.Material arg1);
	public int getStatistic(org.bukkit.Statistic arg0, org.bukkit.entity.EntityType arg1);
	public void setStatistic(org.bukkit.Statistic arg0, org.bukkit.Material arg1, int arg2);
	public void setStatistic(org.bukkit.Statistic arg0, int arg1);
	public void setStatistic(org.bukkit.Statistic arg0, org.bukkit.entity.EntityType arg1, int arg2);
	public int getLevel();
	public void hidePlayer(org.bukkit.entity.Player arg0);
	public float getFlySpeed();
	public void setMaxHealth(double arg0);
	public double getEyeHeight();
	public double getEyeHeight(boolean arg0);
	public boolean canSee(org.bukkit.entity.Player arg0);
	public void sendMap(org.bukkit.map.MapView arg0);
	public void chat(java.lang.String arg0);
	public boolean hasAchievement(org.bukkit.Achievement arg0);
	public void sendSignChange(org.bukkit.Location arg0, java.lang.String[] arg1);
	public boolean isSleepingIgnored();
	public void sendRawMessage(java.lang.String arg0);
	public boolean performCommand(java.lang.String arg0);
	public void sendBlockChange(org.bukkit.Location arg0, org.bukkit.Material arg1, byte arg2);
	public void sendBlockChange(org.bukkit.Location arg0, int arg1, byte arg2);
	public void awardAchievement(org.bukkit.Achievement arg0);
	public void removeAchievement(org.bukkit.Achievement arg0);
	public void incrementStatistic(org.bukkit.Statistic arg0, org.bukkit.entity.EntityType arg1);
	public void incrementStatistic(org.bukkit.Statistic arg0, org.bukkit.entity.EntityType arg1, int arg2);
	public void incrementStatistic(org.bukkit.Statistic arg0, org.bukkit.Material arg1);
	public void incrementStatistic(org.bukkit.Statistic arg0);
	public void incrementStatistic(org.bukkit.Statistic arg0, org.bukkit.Material arg1, int arg2);
	public void incrementStatistic(org.bukkit.Statistic arg0, int arg1);
	public void setCompassTarget(org.bukkit.Location arg0);
	public boolean sendChunkChange(org.bukkit.Location arg0, int arg1, int arg2, int arg3, byte[] arg4);
	public java.lang.String getPlayerListName();
	public void setPlayerListName(java.lang.String arg0);
	public org.bukkit.Location getCompassTarget();
	public void setSleepingIgnored(boolean arg0);
	public long getPlayerTimeOffset();
	public void setBedSpawnLocation(org.bukkit.Location arg0, boolean arg1);
	public void setBedSpawnLocation(org.bukkit.Location arg0);
	public void removeDisconnectingPlayer(org.bukkit.entity.Player arg0);
	public boolean beginConversation(org.bukkit.conversations.Conversation arg0);
	public void sendSupportedChannels();
	public void decrementStatistic(org.bukkit.Statistic arg0, org.bukkit.Material arg1);
	public void decrementStatistic(org.bukkit.Statistic arg0, org.bukkit.entity.EntityType arg1);
	public void decrementStatistic(org.bukkit.Statistic arg0, org.bukkit.Material arg1, int arg2);
	public void decrementStatistic(org.bukkit.Statistic arg0, org.bukkit.entity.EntityType arg1, int arg2);
	public void decrementStatistic(org.bukkit.Statistic arg0);
	public void decrementStatistic(org.bukkit.Statistic arg0, int arg1);
	public void resetPlayerTime();
	public void setTexturePack(java.lang.String arg0);
	public void setHealthScaled(boolean arg0);
	public boolean isHealthScaled();
	public int getTotalExperience();
	public void setHealthScale(double arg0);
	public double getHealthScale();
	public void injectScaledMaxHealth(java.util.Collection arg0, boolean arg1);
	public void abandonConversation(org.bukkit.conversations.Conversation arg0);
	public void abandonConversation(org.bukkit.conversations.Conversation arg0, org.bukkit.conversations.ConversationAbandonedEvent arg1);
	public void setTotalExperience(int arg0);
	public void acceptConversationInput(java.lang.String arg0);
	public boolean isPlayerTimeRelative();
	public void setAllowFlight(boolean arg0);
	public void setFirstPlayed(long arg0);
	public void setDisplayName(java.lang.String arg0);
	public void setOp(boolean arg0);
	public void setBanned(boolean arg0);
	public void loadData();
	public boolean isWhitelisted();
	public java.util.Map serialize();
	public long getLastPlayed();
}
